
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aura Lintang
 */
public class Rental extends javax.swing.JFrame {

    /**
     * Creates new form Rental
     */
    public Rental() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        polisi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nopol = new javax.swing.JTextField();
        struk = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        kembali = new com.toedter.calendar.JDateChooser();
        pinjam = new com.toedter.calendar.JDateChooser();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Vijaya", 1, 50)); // NOI18N
        jLabel9.setText("G L Y P H X I");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        jLabel10.setText("Rental Motor");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 90, 20));

        polisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis Motor --", "Vario", "Beat", "Vega ZR", "Bebek", "SupraX" }));
        polisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polisiActionPerformed(evt);
            }
        });
        jPanel1.add(polisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 190, -1));

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 10));

        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 10));

        jLabel5.setText("No Polisi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 10));

        jLabel4.setText("No Struk");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 10));

        nopol.setEditable(false);
        nopol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolActionPerformed(evt);
            }
        });
        jPanel1.add(nopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 190, -1));
        jPanel1.add(struk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 190, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, -1));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, 30));

        jLabel6.setText("Tgl Pinjam");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, 10));

        jLabel7.setText("Tgl Kembali");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, 10));

        jLabel8.setText("Harga Rental");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, 10));

        harga.setEditable(false);
        harga.setText("Rp 20.000/hari");
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 190, -1));
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 190, -1));
        jPanel1.add(pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 190, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        btnDelete.setText("Delete");
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "No Struk", "No Polisi", "Tgl Pinjam", "Tgl Kembali", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 830, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 440));

        setBounds(0, 0, 845, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Rental Motor GLYPHXI");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
        String tglp = dateFormat.format(pinjam.getDate());
        String tglk = dateFormat.format(kembali.getDate());
        
        Date date1 = pinjam.getDate();
        Date date2 = kembali.getDate();
        long differenceInMilliseconds = date2.getTime() - date1.getTime();
        int differenceInDays = (int)differenceInMilliseconds/(1000*60*60*24);
        Integer hargatotal = differenceInDays*20000;
                
      
        if(nama.getText().equals("") || alamat.getText().equals("") || 
                    struk.getText().equals("") ||
                    nopol.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                String SQL = "INSERT INTO peminjaman(nama, alamat, no_struk, "
                        + "no_pol, tgl_pinjam, tgl_kembali, harga) VALUES "
                        + "('"+nama.getText()+"',"
                        + "'"+alamat.getText()+"','"+struk.getText()+"','"+nopol+"')";
                int status = KoneksiDB.execute(SQL);
                if(status==1){
                    JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan","SUKSES",
                            JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                }else {
                    JOptionPane.showMessageDialog(this,"Data Gagal Ditambahkan","GAGAL",
                            JOptionPane.WARNING_MESSAGE);
                }
            } 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void polisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polisiActionPerformed
        // TODO add your handling code here:
        if(polisi.getSelectedItem().equals("Vario")){
            nopol.setText("N 1234 KY");
        } else if (polisi.getSelectedItem().equals("Beat")){
            nopol.setText("N 7878 LT");
        } else if (polisi.getSelectedItem().equals("Vega ZR")){
            nopol.setText("N 649 ET");
        } else if (polisi.getSelectedItem().equals("Bebek")){
            nopol.setText("N 100 K");
        } else if (polisi.getSelectedItem().equals("Supra X")){
            nopol.setText("N 364 RA");
        } 
    }//GEN-LAST:event_polisiActionPerformed

     private void selectData() {
        String kolom[] = {"Nama", "Alamat", "No_struk", "No_pol", "Tgl_pinjam", 
            "Tgl_kembali", "Harga"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL = "SELECT * FROM `peminjaman`";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()) {
                        String Nama = rs.getString(1);
                        String Alamat = rs.getString(2);
                        String No_struk = rs.getString(3);
                        String No_pol = rs.getString(4);
                        String Tgl_pinjam = rs.getString(5);
                        String Tgl_kembali = rs.getString(6);
                        String Harga = rs.getString(7);
                        String data[] = {Nama, Alamat, No_struk, No_pol, 
                            Tgl_pinjam, Tgl_kembali, Harga};
                        dtm.addRow(data);
                    }
                }    
                catch (SQLException ex) {
                    Logger.getLogger(Rental.class.getName()).log(Level.SEVERE, null, ex);
                }
                tblData.setModel(dtm);
    }
     
    private void nopolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopolActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        alamat.setText("");
        struk.setText("");
        nopol.setText("");
        pinjam.setDate(null);
        kembali.setDate(null);
        harga.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nopol;
    private com.toedter.calendar.JDateChooser pinjam;
    private javax.swing.JComboBox<String> polisi;
    private javax.swing.JTextField struk;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

   
}
